export const countries = [
  { value: "United States", label: "United States" },
  { value: "China", label: "China" },
  { value: "India", label: "India" },
  { value: "Russia", label: "Russia" },
  { value: "Brazil", label: "Brazil" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Germany", label: "Germany" },
  { value: "France", label: "France" },
  { value: "Japan", label: "Japan" },
  { value: "Italy", label: "Italy" },
  { value: "Canada", label: "Canada" },
  { value: "Australia", label: "Australia" },
  { value: "South Korea", label: "South Korea" },
  { value: "Spain", label: "Spain" },
  { value: "Mexico", label: "Mexico" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Turkey", label: "Turkey" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Argentina", label: "Argentina" },
  { value: "Sweden", label: "Sweden" },
  { value: "Poland", label: "Poland" },
  { value: "Belgium", label: "Belgium" },
  { value: "Norway", label: "Norway" },
  { value: "Austria", label: "Austria" },
  { value: "Iran", label: "Iran" },
  { value: "Thailand", label: "Thailand" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Israel", label: "Israel" },
  { value: "South Africa", label: "South Africa" },
  { value: "Denmark", label: "Denmark" },
  { value: "Singapore", label: "Singapore" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Egypt", label: "Egypt" },
  { value: "Ireland", label: "Ireland" },
  { value: "Philippines", label: "Philippines" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Portugal", label: "Portugal" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Colombia", label: "Colombia" },
  { value: "Finland", label: "Finland" },
  { value: "Chile", label: "Chile" },
  { value: "Greece", label: "Greece" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Romania", label: "Romania" },
  { value: "Iraq", label: "Iraq" },
  { value: "Peru", label: "Peru" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Hungary", label: "Hungary" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Qatar", label: "Qatar" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Morocco", label: "Morocco" },
  { value: "Angola", label: "Angola" },
  { value: "Algeria", label: "Algeria" },
  { value: "Oman", label: "Oman" },
  { value: "Sudan", label: "Sudan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Ghana", label: "Ghana" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Cuba", label: "Cuba" },
  { value: "Jordan", label: "Jordan" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Serbia", label: "Serbia" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Panama", label: "Panama" },
  { value: "Croatia", label: "Croatia" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Belarus", label: "Belarus" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Palestine", label: "Palestine" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Nepal", label: "Nepal" },
  { value: "Bolivia", label: "Bolivia" },
];

export const mealGroup = [
  { value: "Cold appetizers", label: "Cold appetizers" },
  { value: "Hot appetizers", label: "Hot appetizers" },
  { value: "Bread and pastries", label: "Bread and pastries" },
  { value: "Soups", label: "Soups" },
  {
    value: "Sauces, dips, and salad dressings",
    label: "Sauces, dips, and salad dressings",
  },
  { value: "Salads", label: "Salads" },
  { value: "Main dishes", label: "Main dishes" },
  { value: "Side dishes and stews", label: "Side dishes and stews" },
  { value: "Desserts", label: "Desserts" },
  { value: "Beverages", label: "Beverages" },
  { value: "Preserves", label: "Preserves" },
];

export const difficulty = [
  { value: "Easy", label: "Easy" },
  { value: "Medium", label: "Medium" },
  { value: "Hard", label: "Hard" },
];

export const events = [
  { value: "Christmas Eve", label: "Christmas Eve" },
  { value: "Christmas", label: "Christmas" },
  { value: "New Year", label: "New Year" },
  { value: "Party", label: "Party" },
  { value: "Carnival", label: "Carnival" },
  { value: "Birthday", label: "Birthday" },
  { value: "Barbecue", label: "Barbecue" },
  { value: "New Year's Eve", label: "New Year's Eve" },
  { value: "Everyday", label: "Everyday" },
  { value: "Easter", label: "Easter" },
  { value: "Valentine's Day", label: "Valentine's Day" },
];

export const seasons = [
  { value: "Spring", label: "Spring" },
  { value: "Summer", label: "Summer" },
  { value: "Autumn/Fall", label: "Autumn/Fall" },
  { value: "Winter", label: "Winter" },
];

export const sortData = [
  { value: "", label: "Date" },
  { value: "rating", label: "Rating" },
];
