server:
    port: 8080
frontend:
    url: ${FRONTEND_URL}
rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 1234
        url: jdbc:postgresql://localhost:5432/coolinarka
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: auditevents, beans, conditions, configprops, env, flyway, health, heapdump, info, liquibase, logfile, loggers, metrics, prometheus, scheduledtasks, sessions, shutdown, threaddump
springdoc:
    api-docs:
        path: /api-docs
